language: node_js

node_js:
  - "10.7.0"

script: npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: www
  target-branch: gh-pages
  on:
    branch: master
